src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Car;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;

Route::resource('cars', 'CarController');
Route::get('/cars/{car}/delete',
    'CarController@destroy')->name('cars.destroy');

Route::resource('drivers', 'DriverController');
Route::get('/drivers/{driver}/delete',
    'DriverController@destroy')->name('drivers.destroy');

//Route::get('/cars', 'CarController@index');
//
//Route::get('/cars/create', 'CarController@create');
//Route::post('/cars/create', 'CarController@store');
//
//Route::get('/cars/{car}/edit', 'CarController@edit');
//Route::put('/cars/{car}', 'CarController@update');
//Route::get('/cars/{car}', 'CarController@show');
//

//Route::get('/', function () {
////    $car = new Car();
////    $car->brand = 'KIA';
////    $car->model = 'ceed';
////    $car->save();
//
////    $data = [
////        'brand' => 'Dodge',
////        'model' => 'Challenger',
////        'number' => 'Т873КУ777',
////    ];
////    Car::create($data);
//
////    $cars = Car::where('model', 'Camry')
////        ->orWhere('model', 'Corolla')->get();
//
////    $cars = Car::where('model', 'Camry')
////        ->orWhere('model', 'Corolla')->update(['brand' => 'TOYOTA']);
//
////    Car::destroy(1);
////    Car::findOrFail(1)->destroy();
//
////    $cars = Car::all();
////    dd(($cars ?? collect())->toArray());
//
////    $cars = Car::all();
////    return view('welcome', ['cars' => $cars]);
//});

src/app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    protected $guarded = ['id'];

//    protected $fillable = ['brand', 'number', 'model'];

    public function driver()
    {
        return $this->belongsTo(Driver::class);
    }
}

src/app/Driver.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Driver extends Model
{
    protected $guarded = ['id'];

//    protected $fillable = ['brand', 'number', 'model'];

    public function cars()
    {
        return $this->hasMany(Car::class);
    }
}

src/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

src/app/Http/Controllers/CarController.php
<?php


namespace App\Http\Controllers;


use App\Car;
use App\Driver;
use App\Http\Requests\StoreCarRequest;
use Illuminate\Http\Request;

class CarController extends Controller
{
    public function index(Request $request)
    {
        $cars = Car::all();
        return view('cars', ['cars' => $cars]);
    }

    public function create(Request $request)
    {
        $drivers = Driver::all();
        return view('create-car', ['drivers' => $drivers]);
    }

    public function store(StoreCarRequest $request)
    {
        Car::create($request->all());

        return redirect(route('cars.index'));
    }

    public function edit(Request $request, Car $car)
    {
        $drivers = Driver::all();
        return view('create-car', [
            'car' => $car,
            'drivers' => $drivers,
        ]);
    }

    public function update(Request $request, Car $car)
    {
        $this->validate($request, [
            'model' => 'required',
            'brand' => 'required',
            'number' => 'nullable|string|max:9|unique:cars,number,' . $car->id,
        ]);

        $car->update($request->all());

        return redirect(route('cars.index'));
    }

    public function destroy(Request $request, Car $car)
    {
        $car->delete();

        return redirect(route('cars.index'));
    }
}

src/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

src/app/Http/Controllers/DriverController.php
<?php


namespace App\Http\Controllers;


use App\Car;
use App\Driver;
use App\Http\Requests\StoreCarRequest;
use Illuminate\Http\Request;

class DriverController extends Controller
{
    public function index(Request $request)
    {
        $drivers = Driver::all();
        return view('drivers', ['drivers' => $drivers]);
    }

    public function create(Request $request)
    {
        return view('create-driver');
    }

    public function store(Request $request)
    {
        Driver::create($request->all());

        return redirect(route('drivers.index'));
    }

    public function edit(Request $request, Driver $driver)
    {
        return view('create-driver', ['driver' => $driver]);
    }

    public function update(Request $request, Driver $driver)
    {
//        $this->validate($request, [
//            'model' => 'required',
//            'brand' => 'required',
//            'number' => 'nullable|string|max:9|unique:cars,number,' . $car->id,
//        ]);

        $driver->update($request->all());

        return redirect(route('drivers.index'));
    }

    public function destroy(Request $request, Driver $driver)
    {
        $driver->delete();

        return redirect(route('drivers.index'));
    }
}

src/resources/views/cars.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Автомобили</title>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
</head>
<body>
<ol>
    @foreach($cars as $index => $car)
        <li>
            <div>
                <strong>ID:</strong> {{$car->id}}
            </div>
            <div>
                <strong>Марка:</strong> {{$car->brand}}
            </div>
            <div>
                <strong>Модель:</strong> {{$car->model}}
            </div>
            <div>
                <strong>Гос. номер:</strong> {{$car->number}}
            </div>
            <div>
                <strong>Владелец:</strong> {{$car->driver->last_name}} {{$car->driver->first_name}} {{$car->driver->middle_name}}
            </div>
            <a href="{{route('cars.edit', ['car'=>$car->id])}}">Редактировать автомобиль</a>
            <a style="color: red;"
               href="{{route('cars.destroy', ['car'=>$car->id])}}">Удалить автомобиль</a>
        </li>
        {{--        @if($car != $cars->last())--}}
        {{--            <hr>--}}
        {{--        @endif--}}

        {{--        @if($index != $cars->count()-1)--}}
        {{--            <hr>--}}
        {{--        @endif--}}

        @if(!$loop->last)
            <hr>
        @endif
    @endforeach
</ol>
<a href="{{route('cars.create')}}">Создать новый автомобиль</a>
</body>
</html>

src/resources/views/create-car.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Создание автомобиля</title>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

    <style>
        label {
            display: block;
        }

        form > div {
            margin-bottom: 15px;
        }

        .alert-danger ul {
            padding: 0;
            margin: 0;
        }

        .alert-danger {
            background: red;
            color: white;
            border-radius: 3px;
            font-size: 14px;
            display: inline-block;
            padding: 15px;
        }
    </style>
</head>
<body>
@isset($car)
    <form method="POST" action="{{route('cars.update', ['car'=>$car->id])}}">
        @method('put')
        @csrf
        <div>
            <label for="brand">Марка</label>
            <input id="brand" type="text" name="brand" value="{{$car->brand}}">
        </div>
        <div>
            <label for="model">Модель</label>
            <input id="model" type="text" name="model" value="{{$car->model}}">
        </div>
        <div>
            <label for="number">Гос. номер</label>
            <input id="number" type="text" name="number" value="{{$car->number}}">
        </div>
        <div>
            <label for="driver_id">Владелец</label>
            <select name="driver_id">
                @foreach($drivers as $driver)
                    @if($car->driver_id == $driver->id)
                        <option selected
                                value="{{$driver->id}}">{{$driver->last_name}} {{$driver->first_name}} {{$driver->middle_name}}</option>
                    @else
                        <option
                            value="{{$driver->id}}">{{$driver->last_name}} {{$driver->first_name}} {{$driver->middle_name}}</option>
                    @endif
                @endforeach
            </select>
        </div>
        @if ($errors->any())
            <div>
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        @endif
        <button type="submit">Отправить форму</button>
    </form>
@else
    <form method="POST" action="{{route('cars.store')}}">
        @csrf
        <div>
            <label for="brand">Марка</label>
            <input id="brand" type="text" name="brand" value="{{old('brand')}}">
        </div>
        <div>
            <label for="model">Модель</label>
            <input id="model" type="text" name="model" value="{{old('model')}}">
        </div>
        <div>
            <label for="number">Гос. номер</label>
            <input id="number" type="text" name="number" value="{{old('number')}}">
        </div>
        <div>
            <label for="driver_id">Владелец</label>
            <select name="driver_id">
                @foreach($drivers as $driver)
                    <option
                        value="{{$driver->id}}">{{$driver->last_name}} {{$driver->first_name}} {{$driver->middle_name}}</option>
                @endforeach
            </select>
        </div>
        @if ($errors->any())
            <div>
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        @endif
        <button type="submit">Отправить форму</button>
    </form>
@endisset
</body>
</html>

src/resources/views/create-driver.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Создание водителя</title>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

    <style>
        label {
            display: block;
        }

        form > div {
            margin-bottom: 15px;
        }

        .alert-danger ul {
            padding: 0;
            margin: 0;
        }

        .alert-danger {
            background: red;
            color: white;
            border-radius: 3px;
            font-size: 14px;
            display: inline-block;
            padding: 15px;
        }
    </style>
</head>
<body>
@isset($driver)
    <form method="POST" action="{{route('drivers.update', ['driver'=>$driver->id])}}">
        @method('put')
        @csrf
        <div>
            <label for="last-name">Фамилия</label>
            <input id="last-name" type="text" name="last_name" value="{{$driver->last_name}}">
        </div>
        <div>
            <label for="first-name">Имя</label>
            <input id="first-name" type="text" name="first_name" value="{{$driver->first_name}}">
        </div>
        <div>
            <label for="middle-name">Отчество</label>
            <input id="middle-name" type="text" name="middle_name" value="{{$driver->middle_name}}">
        </div>
        @if ($errors->any())
            <div>
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        @endif
        <button type="submit">Отправить форму</button>
    </form>
@else
    <form method="POST" action="{{route('drivers.store')}}">
        @csrf
        <div>
            <label for="last-name">Фамилия</label>
            <input id="last-name" type="text" name="last_name" value="{{old('last_name')}}">
        </div>
        <div>
            <label for="first-name">Имя</label>
            <input id="first-name" type="text" name="first_name" value="{{old('first_name')}}">
        </div>
        <div>
            <label for="middle-name">Отчество</label>
            <input id="middle-name" type="text" name="middle_name" value="{{old('middle_name')}}">
        </div>
        @if ($errors->any())
            <div>
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        @endif
        <button type="submit">Отправить форму</button>
    </form>
@endisset
</body>
</html>

src/resources/views/drivers.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Водители</title>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
</head>
<body>
<ol>
    @foreach($drivers as $index => $driver)
        <li>
            <div>
                <strong>Фамилия:</strong> {{$driver->last_name}}
            </div>
            <div>
                <strong>Имя:</strong> {{$driver->first_name}}
            </div>
            <div>
                <strong>Отчество:</strong> {{$driver->middle_name}}
            </div>
            <ul>
                @foreach($driver->cars as $car)
                    <li>{{$car->brand}} {{$car->model}}, г.н. {{$car->number}}</li>
                @endforeach
            </ul>

            <a href="{{route('drivers.edit', ['driver'=>$driver->id])}}">Редактировать водителя</a>
            <a style="color: red;"
               href="{{route('drivers.destroy', ['driver'=>$driver->id])}}">Удалить водителя</a>
        </li>
        {{--        @if($car != $cars->last())--}}
        {{--            <hr>--}}
        {{--        @endif--}}

        {{--        @if($index != $cars->count()-1)--}}
        {{--            <hr>--}}
        {{--        @endif--}}

        @if(!$loop->last)
            <hr>
        @endif
    @endforeach
</ol>
<a href="{{route('drivers.create')}}">Создать нового водителя</a>
</body>
</html>